# Generated by Django 2.2 on 2019-04-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 18, 32, 56, 555505)),
        ),
    ]
