# Generated by Django 2.2 on 2019-04-11 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190409_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 14, 58, 51, 388556)),
        ),
        migrations.AddField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 14, 58, 51, 388556)),
        ),
    ]
